name: thescent
display_name: The Scent Theme
version: 1.0.0
author:
  name: "The Scent"
  email: "contact@thescent.com"
  url: ""

meta:
  compatibility:
    from: 1.7.7.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for homepage and simple pages
    layout-left-column:
      name: Two Columns, small left column
      description: A small left column ideal for category navigation
    layout-right-column:
      name: Two Columns, small right column
      description: A small right column ideal for filters or banners

assets:
  use_parent_assets: false
  css:
    all:
      - id: theme-core-css
        path: assets/css/theme.css
        media: all
        priority: 10
      - id: theme-custom-css
        path: assets/css/custom.css
        media: all
        priority: 20
  js:
    all:
      - id: theme-custom-js
        path: assets/js/custom.js
        priority: 200
        position: bottom

global_settings:
  hooks:
    modules_to_hook:
      displayNavFullWidth:
        - ps_mainmenu
      displayTop:
        - ps_customersignin
        - ps_searchbar
      displayHeader:
        - ps_shoppingcart
      displayHome:
        - ps_featuredproducts
      displayFooter:
        - ps_linklist
        - ps_contactinfo
        - ps_customeraccountlinks
      displayFooterBefore:
        - ps_emailsubscription

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width

dependencies:
  modules:
    - ps_mainmenu
    - ps_featuredproducts
    - ps_emailsubscription
    - ps_shoppingcart
    - ps_customersignin
    - ps_searchbar
    - ps_linklist
    - ps_contactinfo
    - ps_customeraccountlinks
