name: thescent
display_name: The Scent Theme
version: 1.0.0
author:
  name: "The Scent"
  email: ""
  url: ""

parent: classic
template_dir: templates

meta:
  compatibility:
    from: 1.7.7.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for homepage and simple pages
    layout-left-column:
      name: Two Columns, small left column
      description: A small left column ideal for category navigation
    layout-right-column:
      name: Two Columns, small right column
      description: A small right column ideal for filters or banners

assets:
  use_parent_assets: false  # Important: disable parent theme assets
  css:
    all:
      - id: theme-main-style
        path: assets/css/custom.css
        media: all
        priority: 100
  js:
    all:
      - id: theme-main-js
        path: assets/js/custom.js
        position: bottom
        priority: 100
      
  # Add required fonts and icons
  external_css:
    - rel: stylesheet
      href: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&family=Montserrat:wght@300;400;500&family=Raleway:wght@400;500;600&display=swap"
    - rel: stylesheet
      href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"

global_settings:
  hooks:
    modules_to_hook:
      displayNavFullWidth:
        - ps_mainmenu
      displayTop:
        - ps_mainmenu
        - ps_searchbar
      displayHeader:
        - ps_shoppingcart
      displayHome:
        - ps_featuredproducts
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
      displayNav1:
        - ps_contactinfo
      displayNav2:
        - ps_customersignin
      displayFooterBefore:
        - ps_emailsubscription
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displayFooterAfter:
        - ps_socialfollow
      
  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    hero_default:
      width: 1920
      height: 1080
      scope: [categories, manufacturers, suppliers]
    about_default:
      width: 800
      height: 600
      scope: [categories]

theme_settings:
  default_layout: layout-full-width

dependencies:
  modules:
    - ps_mainmenu
    - ps_featuredproducts
    - ps_emailsubscription
    - ps_shoppingcart
    - ps_customersignin
    - ps_searchbar
    - ps_linklist
    - ps_contactinfo
    - ps_customeraccountlinks
    - ps_socialfollow
    - ps_categorytree
    - ps_facetedsearch
