name: thescent
display_name: The Scent
version: 1.0.0
author:
  name: "The Scent"
  email: ""
  url: ""

parent: classic
template_dir: templates

meta:
  compatibility:
    from: 1.7.7.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for homepage and simple pages
    layout-left-column:
      name: Two Columns, small left column
      description: A small left column ideal for category navigation
    layout-right-column:
      name: Two Columns, small right column
      description: A small right column ideal for filters or banners

assets:
  use_parent_assets: false
  css:
    all:
      - id: google-fonts
        path: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600&family=Raleway:wght@300;400;500;600&display=swap"
      - id: font-awesome
        path: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      - id: theme-core
        path: assets/css/theme.css
        media: all
        priority: 50
      - id: theme-custom
        path: assets/css/custom.css
        media: all
        priority: 100
  js:
    all:
      - id: theme-core
        path: assets/js/theme.js
        priority: 50
        position: bottom
      - id: theme-custom
        path: assets/js/custom.js
        priority: 100
        position: bottom

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_enable:
      - ps_mainmenu
      - ps_searchbar
      - ps_shoppingcart
      - ps_customersignin
      - ps_linklist
      - ps_emailsubscription
      - ps_featuredproducts
      - ts_testimonials
      - ps_contactinfo
      - ps_socialfollow
      - ps_facetedsearch
      - blockreassurance
    to_disable:
      - ps_imageslider
      - ps_banner

  hooks:
    modules_to_hook:
      displayNavFullWidth:
        - ps_mainmenu
      displayTop:
        - ps_mainmenu
        - ps_searchbar
        - ps_shoppingcart
        - ps_customersignin
      displayNav1:
        - ps_contactinfo
        - ps_languageselector
        - ps_currencyselector
      displayNav2:
        - ps_customersignin
      displayHome:
        - ps_featuredproducts
      displayTestimonials:
        - ts_testimonials
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
      displaySearch:
        - ps_searchbar
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displayProductAdditionalInfo:
        - ps_sharebuttons
      displayReassurance:
        - blockreassurance

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    hero_default:
      width: 1920
      height: 1080
      scope: [categories, manufacturers, suppliers]
    about_default:
      width: 800
      height: 600
      scope: [categories]
    search_preview:
      width: 50
      height: 50
      scope: [products]

theme_settings:
  default_layout: layout-full-width
  layouts:
    index: layout-full-width
    category: layout-left-column
    product: layout-left-column
    contact: layout-full-width
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column

dependencies:
  modules:
    - ps_mainmenu
    - ps_featuredproducts
    - ps_emailsubscription
    - ps_shoppingcart
    - ps_customersignin
    - ps_searchbar
    - ps_linklist
    - ps_contactinfo
    - ps_customeraccountlinks
    - ps_socialfollow
    - ps_categorytree
    - ps_facetedsearch
    - ts_testimonials
    - blockreassurance
    - ps_sharebuttons
  fonts:
    - family: "Cormorant Garamond:wght@400;500;600;700"
      provider: "google"
    - family: "Montserrat:wght@300;400;500;600"
      provider: "google"
    - family: "Raleway:wght@300;400;500;600"
      provider: "google"
  js:
    - id: jquery
      path: assets/js/jquery.min.js
    - id: popper
      path: assets/js/popper.min.js
    - id: bootstrap
      path: assets/js/bootstrap.min.js
    - id: theme
      path: assets/js/theme.js
  css:
    - id: fontawesome
      path: assets/css/fontawesome.min.css
    - id: bootstrap
      path: assets/css/bootstrap.min.css
    - id: theme
      path: assets/css/theme.css
    - id: custom
      path: assets/css/custom.css
